name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.10

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: pnpm i

      - name: Run Lints
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test

      - name: Build
        run: pnpm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: page
          folder: dist
          single-commit: true
